### ISSUE TITLE
Maker - no device matching

### ISSUE THREAD

**Issue by Kokicha** [iancmcc/ouimeaux#100]
I'm trying to get a sensor (triggered/not triggered) status from my Wemo Maker.
I can list the maker ok using the "wemo list" command, but if I use the command:

wemo maker "device_name" sensor (or any other applicable command) I get the response " No device matching device_name.  Ideas?

**Comment by Senna318** [comment]
I have exactly the same problem. "wemo list" or "wemo status" work fine. But triggering the maker gives this error. 

root@xbian ~ # wemo status
Maker: mydevice         Momentary State: 0
                        Sensor not present
root@xbian ~ # wemo maker "mydevice" on
No device found with that name.

Any thoughts?
