### ISSUE TITLE
Interference with OpenVPN?

### ISSUE THREAD

**Issue by halloalexkern** [iancmcc/ouimeaux#105]
Hello,

i don't know if this is a problem of ouimeaux or a misconfiguration of my system, that i don't see ...

The watch.py script was running on my Cubietruck with a WEMO-motion for weeks without problems.

Now i installed Open-VPN, created a virtual interface, some iptables; THEN the watch-script and the "wemo"-command weren't running any more.

After changing the config to bind: 10.0.0.3:54321 (my Cubietruck's IP physical ethernet-IP) the the "wemo"-command was working again, and after restarting(?) the open-VPN i also got a response from the watch-script.

But after a while the motion-response stop and if i want die restart the script i only get the "Device found: ..." message and then nothing more.
When i restart the Open-VPN service, it works again. 

Any ideas?

BTW, my iptables (if it the failure is here?):
iptables -A FORWARD  -s 10.0.0.0/24 -i eth0:0 -o eth0 -m conntrack --ctstate NEW -j REJECT
iptables -A FORWARD -s 10.0.0.0/24 -i eth0:0 -o tun0 -m conntrack --ctstate NEW -j ACCEPT
iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE
(eth0:0 is my virtual ethernet running in the same subnet; tun0 the Open-VPN-tunnel)

Thanks.

:-) AK

**Comment by Tzfardaya** [comment]
Hey, Thanks for this.. I've been pulling my hair out trying to figure out why my wemo(s) stopped replying, I recently set up an openvpn as well, disable it and everything works again...
Doubt it's in your iptables, as I haven't configured mine yet. (or it's that we're both set up to send everything through the vpn)

**Comment by Tzfardaya** [comment]
We're both a little dense... 
Just us the binding tag to force wemo to use the local network..  (wemo -b 192.168.x.x:54321) and it works fine with the VPN active...  

Not a software issue,  pebkac issue...  ;-)
