### ISSUE TITLE
Installation error ?

### ISSUE THREAD

**Issue by todely** [iancmcc/ouimeaux#106]
Hi,
I try to install ouimeaux on raspberry and it's what i get:

pi@TODpi ~ $ sudo pip install ouimeaux
Requirement already satisfied (use --upgrade to upgrade): ouimeaux in /usr/local/lib/python3.2/dist-packages/ouimeaux-0.7.9_r0-py3.2.egg
Requirement already satisfied (use --upgrade to upgrade): gevent>=1.0 in /usr/local/lib/python3.2/dist-packages (from ouimeaux)Requirement already satisfied (use --upgrade to upgrade): requests>=2.3.0 in /usr/local/lib/python3.2/dist-packages (from ouimeaux)
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/local/lib/python3.2/dist-packages/PyYAML-3.11-py3.2-linux-armv7l.egg (from ouimeaux)
Requirement already satisfied (use --upgrade to upgrade): pysignals in /usr/local/lib/python3.2/dist-packages/pysignals-0.1.2-py3.2.egg (from ouimeaux)
Requirement already satisfied (use --upgrade to upgrade): flask-restful in /usr/local/lib/python3.2/dist-packages/Flask_RESTful-0.3.4-py3.2.egg (from ouimeaux)
Requirement already satisfied (use --upgrade to upgrade): gevent-socketio in /usr/local/lib/python3.2/dist-packages/gevent_socketio-0.3.6-py3.2.egg (from ouimeaux)
Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.4.7 in /usr/local/lib/python3.2/dist-packages (from gevent>=1.0->ouimeaux)
Requirement already satisfied (use --upgrade to upgrade): aniso8601>=0.82 in /usr/local/lib/python3.2/dist-packages (from flask-restful->ouimeaux)
Requirement already satisfied (use --upgrade to upgrade): Flask>=0.8 in /usr/local/lib/python3.2/dist-packages (from flask-restful->ouimeaux)
Requirement already satisfied (use --upgrade to upgrade): six>=1.3.0 in /usr/local/lib/python3.2/dist-packages (from flask-restful->ouimeaux)
Requirement already satisfied (use --upgrade to upgrade): pytz in /usr/local/lib/python3.2/dist-packages (from flask-restful->ouimeaux)
Collecting gevent-websocket (from gevent-socketio->ouimeaux)
  Using cached gevent-websocket-0.9.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-ali7kk/gevent-websocket/setup.py", line 4, in <module>
        version = __import__('geventwebsocket').get_version()
      File "geventwebsocket/__init__.py", line 18, in <module>
        from .server import WebSocketServer
      File "geventwebsocket/server.py", line 1, in <module>
        from gevent.pywsgi import WSGIServer
      File "/usr/local/lib/python3.2/dist-packages/gevent/__init__.py", line 41, in <module>
        from gevent.hub import get_hub, iwait, wait
      File "/usr/local/lib/python3.2/dist-packages/gevent/hub.py", line 289
        except Exception, ex:
                        ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ali7kk/gevent-websocket

What's wrong ?

**Comment by todely** [comment]
Invalid syntax pointing at "," after Exception

**Comment by iancmcc** [comment]
You are attempting to use python 3, which is not supported yet. Try Python 2.x.

**Comment by todely** [comment]
How can i choose to use python 2.x ?

**Comment by iancmcc** [comment]
The "pip" you're using is installed into a python3 environment. Install
python 2 using the package manager for your distro, then install pip into
that environment (you may already have it if it's python 2.7.9 or higher),
then use that pip to install ouimeaux.

**Comment by todely** [comment]
I have try easy_install-3.2 ouimeaux and it works like a charm
Thanks for your help
