### ISSUE TITLE
How to start server as background process at startup?

### ISSUE THREAD

**Issue by kammmuschel** [iancmcc/ouimeaux#108]
I have installed Ouimeaux with the server and it works perfectly. I guess my question shows my limited linux experience, but how do I start the server as a background process at startup? I am running it on Raspbian Jessie.

Daniel

**Comment by iancmcc** [comment]
Easiest way is to run it with an ampersand following, which will put it in
the background, then run "disown".

**Comment by kammmuschel** [comment]
Okay, I have figured it out, also how to add it to /etc/init.d. Thank you.
