### ISSUE TITLE
Support for light switch Longpress

### ISSUE THREAD

**Issue by rvanbaalen** [iancmcc/ouimeaux#112]
First of all -- GREAT library! Using a local Ubuntu server in my network + a modified example script, I managed to instantly switch one of my Wemo Switches using the Wemo Lightswitch.

One question remains:
Does your library also support the Longpress of Wemo Light Switches?

**Comment by iancmcc** [comment]
Not currently, but it would be great to add it. I'll keep it on the list
and hope to get it in the next release.

**Comment by rvanbaalen** [comment]
That would be awesome! Let me know if you need me to test any new features. 

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by esev** [comment]
Is this a dup of #60 ?
