### ISSUE TITLE
Device doesn't respond to "Wemo list" but verified on network

### ISSUE THREAD

**Issue by Joelkw** [iancmcc/ouimeaux#130]
I'm having serious trouble connecting to a Wemo Insight.

I have both the cli and python library working. The command "Wemo -d -t 8 list" returns: `DEBUG:ouimeaux.discovery:Binding datagram server to 192.168.1.147:54321
INFO:ouimeaux.environment:Discovering devices
DEBUG:ouimeaux.discovery:Broadcasting M-SEARCH to 239.255.255.250:1900
DEBUG:ouimeaux.discovery:Broadcasting M-SEARCH to 239.255.255.250:1900
DEBUG:ouimeaux.discovery:Broadcasting M-SEARCH to 239.255.255.250:1900
DEBUG:ouimeaux.discovery:Broadcasting M-SEARCH to 239.255.255.250:1900
DEBUG:ouimeaux.discovery:Broadcasting M-SEARCH to 239.255.255.250:1900
DEBUG:ouimeaux.discovery:Broadcasting M-SEARCH to 239.255.255.250:1900
DEBUG:ouimeaux.discovery:Broadcasting M-SEARCH to 239.255.255.250:1900
DEBUG:ouimeaux.discovery:Broadcasting M-SEARCH to 239.255.255.250:1900`

or no devices found. I have the device IP address and port like #113 asks, but it was never answered. I think the easiest thing to do would be to hardcode it somewhere, but I can't seem to figure out where in the code. 

I have Upnp enabled on the wifi router. I tried disabling the firewall, which did nothing. I can visit the device http://192.168.1.145:49153/setup.xml so I know what port and IP address it has. I'm not sure why the device is not responding to the broadcast but am open to any ideas! It is running WeMo_WW_2.00.10626.PVT-OWRT-InsightV2 and I am running OSX 10.11.5 (El Capitan). Thanks!

**Comment by AlexBroughton** [comment]
I'm having the same problem. Your device is connected to the right network right (wemo list command returns all of the connected devices)?

**Comment by bunnyroo** [comment]
Did you ever solve this? All my devices are found except for one Insight switch that connects to a wifi extender. I see it on the network, the WeMo app sees it, but ouimeaux misses it somehow.

**Comment by ki4070ma** [comment]
I'm having same problem.

* I see it on the network by arp-scan

```
$sudo arp-scan -I wlp3s0 -l
(...snip...)
192.168.11.21	(mac addr)	Belkin International Inc.
```

* the WeMo app sees it from android, iOS

* I can visit the device, http://192.168.11.21:49153/setup.xml

* ouimeaux misses it

```
➜  ~ wemo -d list                                 
DEBUG:ouimeaux.discovery:Binding datagram server to 192.168.11.15:54321
INFO:ouimeaux.environment:Discovering devices
DEBUG:ouimeaux.discovery:Broadcasting M-SEARCH to 239.255.255.250:1900
DEBUG:ouimeaux.discovery:Broadcasting M-SEARCH to 239.255.255.250:1900
DEBUG:ouimeaux.discovery:Broadcasting M-SEARCH to 239.255.255.250:1900
DEBUG:ouimeaux.discovery:Broadcasting M-SEARCH to 239.255.255.250:1900
DEBUG:ouimeaux.discovery:Broadcasting M-SEARCH to 239.255.255.250:1900
```

**Comment by ki4070ma** [comment]
I could find wemo device from Raspberry Pi. It means my laptop PC couldn't find wemo device somehow...
