### ISSUE TITLE
WeMo LED lights not using passed dim value.

### ISSUE THREAD

**Issue by flackr** [iancmcc/ouimeaux#132]
I've tried both using the python command and the command-line wemo command to dim lights but neither work, i.e.:
bridge.light_set_state(lights[light_name], state=1, dim=100)
OR:
wemo light light_name on 100

Neither of these actually change the light dim value, but the commands do work to change the state on or off. The lights are running firmware version 83 and the WeMo link is running firmware WeMo_WW_2.00.10626.PVT-OWRT-Link. Perhaps the command to change the intensity/dimming value has changed?

**Comment by tfasz** [comment]
I noticed the same thing recently - dimming did not work from the command line or API but still worked from the Belkin Wemo iOS application. I'm guessing this was a change in the firmware. After looking into it more, I noticed the light_set_state call was always passing both the state and dim values (CapabilityID=10006 AND CapabilityID=10008). I made a change to only pass in one CapabilityID at a time and it fixed the issue. 

Here is what I changed the light_set_state call to in bridge.py - you can pass in either state or dim but not both. I also added a transition_duration that can be set when dimming.
```
    def light_set_state(self, light, state=None, dim=None, transition_duration=0):
        if not state == None:
            sendState = '&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;DeviceStatus&gt;&lt;IsGroupAction&gt;NO&lt;/IsGroupAction&gt;&lt;DeviceID available=&quot;YES&quot;&gt;{devID}&lt;/DeviceID&gt;&lt;CapabilityID&gt;10006&lt;/CapabilityID&gt;&lt;CapabilityValue&gt;{state}&lt;/CapabilityValue&gt;&lt;/DeviceStatus&gt;'.format(devID=self.light_get_id(light),state=state)
        elif not dim == None:
            sendState = '&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;DeviceStatus&gt;&lt;IsGroupAction&gt;NO&lt;/IsGroupAction&gt;&lt;DeviceID available=&quot;YES&quot;&gt;{devID}&lt;/DeviceID&gt;&lt;CapabilityID&gt;10008&lt;/CapabilityID&gt;&lt;CapabilityValue&gt;{dim}:{duration}&lt;/CapabilityValue&gt;&lt;/DeviceStatus&gt;'.format(devID=self.light_get_id(light),dim=dim,duration=transition_duration)

        return self.bridge.SetDeviceStatus(DeviceStatusList=sendState)
```

So now if I want to fade a light off over 10 seconds I can call:
```
bridge.light_set_state(bridge.Lights[light], dim="0", transition_duration="100")
time.sleep(10)
bridge.light_set_state(bridge.Lights[light], state="0")
```

Happy to submit a merge request with the changes, but this would also require some changes to the CLI, docs, etc. that I have not done.

**Comment by emunsing** [comment]
This is incredibly helpful, @tfasz - I spent the past ~2 hours trying to debug my code and the package code before finding this. If you get a chance, a merge request would be immensely helpful!
