### ISSUE TITLE
Import error with python 3

### ISSUE THREAD

**Issue by DIYtechie** [iancmcc/ouimeaux#136]
Hi all. Noob here.

I have made a simple script that works, when I run it in python 2.7 (python /home/pi/mypython/Wemo_script.py) on my raspberry pi.

However, when I try to run it with python 3.4 (python3 /home/pi/mypython/Wemo_script.py) I get an import error from the greenlet dependency:

```
pi@raspberrypi:~ $ python3 /home/pi/mypython/Wemo_script.py
Traceback (most recent call last):
  File "/home/pi/mypython/Wemo_script.py", line 8, in <module>
    from ouimeaux.environment import Environment
  File "/usr/local/lib/python3.4/dist-packages/ouimeaux/environment.py", line 3, in <module>
    import gevent
  File "/usr/local/lib/python3.4/dist-packages/gevent/__init__.py", line 49, in <module>
    from gevent.hub import get_hub, iwait, wait, PYPY
  File "/usr/local/lib/python3.4/dist-packages/gevent/hub.py", line 11, in <module>
    from greenlet import greenlet, getcurrent, GreenletExit
ImportError: /usr/local/lib/python3.4/dist-packages/greenlet.so: undefined symbol: _Py_ZeroStruct
```

I tried reinstalling ouimeaux: 
`sudo pip install ouimeaux --target=/usr/local/lib/python3.4/dist-packages/`
and greenlet:
`sudo pip install greenlet --target=/usr/local/lib/python3.4/dist-packages/`

but I still can't get it to work. I keep getting the greenlet import error (undefined symbol: _Py_ZeroStruct). 

Can anyone help me solve this issue?

My simple script (Wemo_script.py):

```
#!/usr/bin/env /usr/bin/python3
# -*- coding: utf-8 -*-

import time

import ouimeaux

from ouimeaux.environment import Environment

def on_switch(switch):
        print ("Switch found!", switch.name)

env = Environment(on_switch)

try:
        env.start()
except Exception:
        import datetime
        print('Der skete en fejl (WeMo): {:%Y-%m-%d %H:%M:%S}'.format(datetime.datetime.now()))

env.list_switches()

switch = env.get_switch('WeMo')

switch.basicevent.SetBinaryState(BinaryState=1)

time.sleep(2)

switch.basicevent.SetBinaryState(BinaryState=0)
```

**Comment by PiRune** [comment]
My bad. The import error is solved by using pip3 install instead of pip.

**Comment by PiRune** [comment]
Should have been installed using pip3. My bad. Feel free to close this issue.
