### ISSUE TITLE
Does it support "Wemo Mini Smart Plug"?

### ISSUE THREAD

**Issue by yeralin** [iancmcc/ouimeaux#154]
Does the library support "Wemo Mini Smart Plug"?

**Comment by iancmcc** [comment]
Probably not yet, but it's a simple addition. If you've got one we can add the support pretty quickly. I don't have one yet.

**Comment by yeralin** [comment]
Yep, I have one. You can explain the process to me, and I can try myself

**Comment by yeralin** [comment]
@iancmcc ?

**Comment by iancmcc** [comment]
Sorry, I haven't forgotten, but my day job got extremely busy.

The basic idea is simply to watch logging during discovery (i.e., run `wemo -d list`) and look for this log message:
https://github.com/iancmcc/ouimeaux/blob/develop/ouimeaux/environment.py#L137

Assuming that the smart plug has its own USN, you'll get it logged, and then it's a simple matter of adding it to the checks right above that log message, probably using `klass = Switch` (if it has extra functionality, it could have its own class to support that, but Switch will most likely work).

**Comment by yeralin** [comment]
@iancmcc Actually, it worked w/o any changes.

I ran `wemo list`
and it recognized "Wemo Mini Smart Plug" as `('Switch:', 'Wemo Mini')`
