### ISSUE TITLE
@receiver(statechange) not getting trigger with watch.py

### ISSUE THREAD

**Issue by lp27** [iancmcc/ouimeaux#158]
How do I go about debugging @receiver(statechange) not getting trigger?

I ran watch.py in one terminal and I ran wemo cli to turn on a switch on another terminal.
But I don't see @receiver(statechange) get trigger.

Thanks.

Update:  Problem look similar to bug #119

**Comment by minscof** [comment]
same problem here. Has someone an explanation ? thx

**Comment by fiberwings** [comment]
Same problem here. I had to upgrade to the latest version of of the library and this problem show up so I think it may be a bug introduced along the way.

**Comment by maheshvra** [comment]
Same here

**Comment by stephenwilley** [comment]
Same here.  Trying to figure out why...
