### ISSUE TITLE
Address already in use error 

### ISSUE THREAD

**Issue by Judas2016** [iancmcc/ouimeaux#165]
Hi,

I am starting to have "error: [Errno 98] Address already in use: ('', 8354)" errors in an application I wrote.  The application schedules a check for the wemo status every 10 minutes, and toggles lights on/off based on schedule.  Im finding that the application will run fine for hours, but at some point starts showing the error, rebooting the RPI fixes the issue.  Below is the full stack trace. I confirmed I am using the most recent release of Ouimeaux. 

**Anyone have any idea what's causing this or workaround?** 

Oct 13 09:08:16 wiab-prod server.py[395]: 2017-10-13 09:08:16,133 - WIAB.core.wemo - DEBUG - starting wemo discovery
Oct 13 09:08:16 wiab-prod server.py[395]: Traceback (most recent call last):
Oct 13 09:08:16 wiab-prod server.py[395]: File "/var/wiab/src/server/../../src/controllers/wemo.py", line 17, in setwemostate
Oct 13 09:08:16 wiab-prod server.py[395]: env.start()
Oct 13 09:08:16 wiab-prod server.py[395]: File "/usr/local/lib/python2.7/dist-packages/ouimeaux-0.8-py2.7.egg/ouimeaux/environment.py", line 86, in start
Oct 13 09:08:16 wiab-prod server.py[395]: self.registry.server.start()
Oct 13 09:08:16 wiab-prod server.py[395]: File "/usr/local/lib/python2.7/dist-packages/gevent-1.2.1-py2.7-linux-armv7l.egg/gevent/baseserver.py", line 304, in start
Oct 13 09:08:16 wiab-prod server.py[395]: self.init_socket()
Oct 13 09:08:16 wiab-prod server.py[395]: File "/usr/local/lib/python2.7/dist-packages/gevent-1.2.1-py2.7-linux-armv7l.egg/gevent/pywsgi.py", line 1451, in init_socket
Oct 13 09:08:16 wiab-prod server.py[395]: StreamServer.init_socket(self)
Oct 13 09:08:16 wiab-prod server.py[395]: File "/usr/local/lib/python2.7/dist-packages/gevent-1.2.1-py2.7-linux-armv7l.egg/gevent/server.py", line 127, in init_socket
Oct 13 09:08:16 wiab-prod server.py[395]: self.socket = self.get_listener(self.address, self.backlog, self.family)
Oct 13 09:08:16 wiab-prod server.py[395]: File "/usr/local/lib/python2.7/dist-packages/gevent-1.2.1-py2.7-linux-armv7l.egg/gevent/server.py", line 138, in get_listener
Oct 13 09:08:16 wiab-prod server.py[395]: return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
Oct 13 09:08:16 wiab-prod server.py[395]: File "/usr/local/lib/python2.7/dist-packages/gevent-1.2.1-py2.7-linux-armv7l.egg/gevent/server.py", line 228, in _tcp_listener
Oct 13 09:08:16 wiab-prod server.py[395]: sock.bind(address)
Oct 13 09:08:16 wiab-prod server.py[395]: File "<string>", line 1, in bind
Oct 13 09:08:16 wiab-prod server.py[395]: error: [Errno 98] Address already in use: ('', 8354)
Oct 13 09:08:16 wiab-prod server.py[395]: 2017-10-13 09:08:16,150 - WIAB.core.wemo - ERROR - {'tentid': 1, 'error': None, 'Switch': u'Tent Light 1', 'module': 'WeMo Controller', 'time': 1507900096.148918}
Oct 13 09:08:16 wiab-prod server.py[395]: Traceback (most recent call last):
Oct 13 09:08:16 wiab-prod server.py[395]: File "/var/wiab/src/server/../../src/api/controller/lightplant.py", line 33, in lightplant
Oct 13 09:08:16 wiab-prod server.py[395]: wemo.setwemostate(switchname, True, tentid)
Oct 13 09:08:16 wiab-prod server.py[395]: File "/var/wiab/src/server/../../src/api/controller/wemo.py", line 10, in setwemostate
Oct 13 09:08:16 wiab-prod server.py[395]: return wemo.setwemostate(switchname, lighton, tentid)
Oct 13 09:08:16 wiab-prod server.py[395]: File "/var/wiab/src/server/../../src/controllers/wemo.py", line 33, in setwemostate
Oct 13 09:08:16 wiab-prod server.py[395]: raise ControllerException(msg)
Oct 13 09:08:16 wiab-prod server.py[395]: ControllerException: {'tentid': 1, 'error': None, 'Switch': u'Tent Light 1', 'module': 'WeMo Controller', 'time': 1507900096.148918}
Oct 13 09:08:16 wiab-prod server.py[395]: 2017-10-13 09:08:16,152 - WIAB.core.lightplant - ERROR - {'tentid': 1, 'switchname': u'Tent Light 1', 'error': None, 'time': 1507900096.15141}
Oct 13 09:08:16 wiab-prod server.py[395]: Traceback (most recent call last):
Oct 13 09:08:16 wiab-prod server.py[395]: File "/var/wiab/src/server/server.py", line 64, in get_status
Oct 13 09:08:16 wiab-prod server.py[395]: sensor_list[i]['houron'], sensor_list[i]['houroff'])
Oct 13 09:08:16 wiab-prod server.py[395]: File "/var/wiab/src/server/../../src/api/controller/lightplant.py", line 40, in lightplant
Oct 13 09:08:16 wiab-prod server.py[395]: raise ControllerException(msg)
Oct 13 09:08:16 wiab-prod server.py[395]: ControllerException: {'tentid': 1, 'switchname': u'Tent Light 1', 'error': None, 'time': 1507900096.15141}
Oct 13 09:08:16 wiab-prod server.py[395]: 2017-10-13 09:08:16,153 - WIAB.core.exceptions - CRITICAL - None

**Comment by Judas2016** [comment]
Here is the code block that is causing the error. With or without the cache disabled makes no difference. 

def setwemostate(switchname, lighton, tentid):
    logger = log.initialize_logger('WIAB.core.wemo')
    try:
        logger.info("wemo_control.py %s", VERSION)
        logger.debug("starting wemo discovery")
        env = Environment(with_cache=False)
        env.start()
        env.discover(seconds=10)  # wait 10 seconds for discovery
        logger.debug("switches found: %s", env.list_switches())
        wswitch = env.get_switch(switchname)
        logger.debug("Switch state is: %s and status should be %s", wswitch.get_state(), lighton)

        if lighton != wswitch.get_state():
            if lighton == True:
                logger.debug("turning light on")
                wswitch.on()
            else:
                logger.debug("turning light off")
                wswitch.off()
    except:
        msg = {"time": time.time(), "tentid": tentid, "module": "WeMo Controller", "error": traceback.print_exc(), "Switch": switchname}
        logger.error(msg)
        raise ControllerException(msg)
    finally:
        wswitch = None
        env = None

**Comment by Bizzaro** [comment]
same issue...

**Comment by m-ric** [comment]
Same issue here. Happens randomly in my unit-test
