### ISSUE TITLE
cant install server

### ISSUE THREAD

**Issue by madmartian5** [iancmcc/ouimeaux#167]
Hi there,
I installed ouimeaux fine with the following command:
`easy_install ouimeaux `

but get the following error when trying to install server:

`no matches found: ouimeaux[server]`

any ideas.. I am on Mac OSX

**Comment by ericksonstudio** [comment]
Try the command: `pip install ouimeaux[server]` to install the server. If that doesn't work, try again using `sudo pip install ouimeaux[server]`.

**Comment by IanPhilips** [comment]
@ericksonstudio  have you tried running as `sudo wemo server`? It only works on my mac if I add `sudo`

**Comment by Caiuse** [comment]
Seams that ouimeaux server is no longer part of the pip repos, you can install it from github repo like so `pip install -e 'git+https://github.com/syphoxy/ouimeaux.git#egg=ouimeaux[server]`
