### ISSUE TITLE
Add support for Wemo Humidifier

### ISSUE THREAD

**Issue by sqldiablo** [iancmcc/ouimeaux#168]
Hi all, would it be possible to add support for the Wemo Humidifier?

Product Page:
[https://www.holmesproducts.com/wemo-humidifier.html](https://www.holmesproducts.com/wemo-humidifier.html)

Another project trying to implement local control of the humidifier:
[https://community.smartthings.com/t/holmes-wemo-humidifier/19482/6](https://community.smartthings.com/t/holmes-wemo-humidifier/19482/6)

**Comment by iancmcc** [comment]
As long as the same protocols are involved, it should be reasonably straightforward.  Adding new types is pretty easy, although the API and CLI get a little messy. I'd love to refactor it all, but there's just no time.

Anyway, it is certainly possible, and I would happily assist anybody who wanted to do so.

**Comment by sqldiablo** [comment]
I've created a pull request to add this to pywemo: https://github.com/pavoni/pywemo/pull/87. Feel free to roll the changes into ouimeaux as well.
