### ISSUE TITLE
ouimeaus installed but server missing dependancies?

### ISSUE THREAD

**Issue by phoniclynx** [iancmcc/ouimeaux#180]
I have installed Ouieaus and the executable works fine. However, when I go to use it as a server it tells me that their dependencies are not installed:
`ouimeaux server dependencies are not installed. Please run, e.g., 'pip install ouimeaux[server]'`
If I do as instructed, it fails with some kind of error. But if I do as instructed in one of the other threads here:

> "pip  install -e 'git+https://github.com/syphoxy/ouimeaux.git#egg=ouimeaux[server]'" 

it seems to install fine with no errors. However, when I try and run "wemo server" again I get the same dependancy errors.

As it's a shame as I would rather CURL to the server than run it as a command line util using PHP.

**Comment by MacauleyCz** [comment]
I have the same issue but the link isn't active anymore, do you know of another method to get around this issue?

**Comment by chrispitude** [comment]
I have the same issue. Has anyone figured this out?

**Comment by touchline3d** [comment]
I think i found a solution
try to uninstall and reinstall Flask with the required version
pip uninstall Flask
pip install Flask==0.8

**Comment by dustball** [comment]
I am having this issue as well and neither of the above solutions do anything.

**Comment by surlyhacker** [comment]
See my description of a fix to this issue [here](https://github.com/iancmcc/ouimeaux/issues/197#issuecomment-709696525)
