### ISSUE TITLE
pip installation in virtualenv asks for github credentials

### ISSUE THREAD

**Issue by cameronSlupeiks** [iancmcc/ouimeaux#188]
Hi there, 

I am trying to get Ouimeaux setup in the virtualenv that I have created. When I enter the last line of the installation sequence, I am prompted to enter my GitHub username and password. When I enter both, I am given an Authentication Failure:

remote: Repository not found.
fatal: Authentication failed for 'https://github.com/syphoxy/ouimeaux.git/'
Command "git clone -q https://github.com/syphoxy/ouimeaux.git /tmp/pip-U3iiHA-build" failed with error code 128 in None

Could someone point me in the right direction? 

Thanks.

**Comment by lrodriguezrullan** [comment]
I am having the same issue.

**Comment by mickeygoldsmith** [comment]
Im having the same issue....any luck fixing the issue?
