### ISSUE TITLE
failed with error code 128 in None

### ISSUE THREAD

**Issue by mickeygoldsmith** [iancmcc/ouimeaux#192]
The installation in virtualenv says that the git location doesn't exist by giving error code 128. 

"(ouimeaux-env) pi@pihole:~/ouimeaux-env $ pip install git+https://github.com/syphoxy/ouimeaux.git
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/syphoxy/ouimeaux.git
  Cloning https://github.com/syphoxy/ouimeaux.git to /tmp/pip-req-build-VUUyHv
  Running command git clone -q https://github.com/syphoxy/ouimeaux.git /tmp/pip-req-build-VUUyHv
Username for 'https://github.com': mickeygoldsmith	
Password for 'https://mickeygoldsmith@github.com': 
  remote: Repository not found.
  fatal: repository 'https://github.com/syphoxy/ouimeaux.git/' not found
ERROR: Command "git clone -q https://github.com/syphoxy/ouimeaux.git /tmp/pip-req-build-VUUyHv" failed with error code 128 in None"

**Comment by BlackLight** [comment]
That's because the https://github.com/syphoxy/ouimeaux repository doesn't actually exist anymore and now it (should) all be merged in https://github.com/iancmcc/ouimeaux
