### ISSUE TITLE
Turn on, then off in REST API

### ISSUE THREAD

**Issue by qrush** [iancmcc/ouimeaux#31]
We've been using ouimeaux at CoworkBuffalo and it's been great. Right now, however, I have to make two API requests in this fashion:
1. POST to turn switch on
2. sleep N seconds (usually 3-5)
3. POST to turn switch off

The main problem here is that if the second API call fails, that's not good. We need some kind of way to say "Turn on, then off after a delay".

Could something like this be built into ouimeaux? Sadly I'm not too familiar with Python or its threading model.

**Comment by mbaturin** [comment]
Is there a way to browse directly to the link of the Web App for one of my switches.  My goal is to save it as a pin on my xbox one called Lights so i can say Xbox Lights and have my living room lights (on a Wemo Switch) turn off and on through voice command.  Currently though I see the buttons are embedded in javascript. 

<a role="button" class="btn btn-lg btn-block ng-binding btn-success" ng-disabled="device.type=='Motion'" ng-click="toggleState(device)" ng-class="{'btn-default': device.state==0, 'btn-success':device.state==1}">
         <span class="btn-icon glyphicon glyphicon-off" ng-class="{
                'glyphicon-off': device.type=='Switch' || 
                                 device.type=='LightSwitch' ||
                                 device.type=='Insight',
                'glyphicon-transfer': device.type=='Motion'
             }"></span>
        Chandelier Light
    </a>

**Comment by iancmcc** [comment]
Yes, see the rest Api docs. You can POST directly to a switch to toggle it. 




http://ouimeaux.readthedocs.org/en/latest/server.html#rest-api

**Comment by mbaturin** [comment]
Thanks for the super fast response - this is awesome by the way.  I am an IT guy but programming isn't my strong suit.  Is there any chance you would be able to give me an example of what the URL might look like to accomplish this?  On the Xbox all I have is Internet explorer so I need to it basically be a permanent URL link that will toggle the switch.

**Comment by iancmcc** [comment]
It's in the docs. /api/device/MYDEVICE I believe, but you have to POST to it so a browser won't work unless you build a form.

**Comment by mbaturin** [comment]
OK Thanks I will give it a shot

**Comment by mbaturin** [comment]
Tried this in my browser: http://10.0.0.5:5000/api/device/Chandelier?state=toggle

All I am getting back is this:

{
    "host": "10.0.0.xxx", 
    "model": "Belkin Plugin Socket 1.0", 
    "name": "Chandelier Light", 
    "serialnumber": "221410K13xxxxx", 
    "state": 1, 
    "type": "LightSwitch"
}

I would really appreciate if you could help me as to the code I would need to put into an HTML file if that is what is needed to browse to and toggle the switch.   I would be willing to donate a small amount to you for that and for all this other great work you've done.  If not, I understand.  I feel like I am so close but not quite able to figure it out.  I tried this futile attempt at an HTML page:

<html>
curl -X POST http://10.0.0.5:5000/api/device/Chandelier?state=toggle
</html>

**Comment by iancmcc** [comment]
Did that curl command not work? It should have. You can technically omit ?state=toggle, since it’s the default.


— Ian

**Comment by mbaturin** [comment]
Yeah I think that is the right command, but I am trying to have it execute automatically when visiting a URL.  Where is that command meant to be run?  In a terminal window?

**Comment by iancmcc** [comment]
Yes. You can probably get a page to auto-POST a form when you load it, although it's a huge security hole so maybe not.
