### ISSUE TITLE
Belkin android app does not play well with others...

### ISSUE THREAD

**Issue by mcfacilitator** [iancmcc/ouimeaux#34]
I don’t know when this started, but I just realized that the Belkin app wreaks havoc on my system when I use it to test the remote feedback.  This wasn’t always true.  Just looking at the upnp chatter, I think it is canceling all the subscriptions for anyone else, and possibly worse.  This took me days to realize that it was the Belkin app because, like I said, this is new.

There are better android alternatives for testing, anyway.

**Comment by iancmcc** [comment]
Closing until it's more widely reported as an issue. I'm not sure what we can do about it anyway.
