### ISSUE TITLE
wemo list output empty

### ISSUE THREAD

**Issue by nfgb** [iancmcc/ouimeaux#45]
I have a wemo switch fully configured. On my raspberry pi (debian) the output of wemo list is empty. I've tried with another PC and the result is the same.
Here's the debug output:
DEBUG:ouimeaux.discovery:Binding datagram server to 192.168.0.10:54321
INFO:ouimeaux.environment:Discovering devices
DEBUG:ouimeaux.discovery:Broadcasting M-SEARCH to 239.255.255.250:1900
DEBUG:ouimeaux.discovery:Received a response from 192.168.0.10:1900
DEBUG:ouimeaux.discovery:Received a response from 192.168.0.1:1901
DEBUG:ouimeaux.discovery:Broadcasting M-SEARCH to 239.255.255.250:1900
DEBUG:ouimeaux.discovery:Received a response from 192.168.0.10:1900
DEBUG:ouimeaux.discovery:Received a response from 192.168.0.1:1901
DEBUG:ouimeaux.discovery:Received a response from 192.168.0.10:44175
DEBUG:ouimeaux.discovery:Received a response from 192.168.0.10:47871
DEBUG:ouimeaux.discovery:Broadcasting M-SEARCH to 239.255.255.250:1900
DEBUG:ouimeaux.discovery:Received a response from 192.168.0.10:1900
DEBUG:ouimeaux.discovery:Received a response from 192.168.0.1:1901
DEBUG:ouimeaux.discovery:Received a response from 192.168.0.10:47881
DEBUG:ouimeaux.discovery:Broadcasting M-SEARCH to 239.255.255.250:1900
DEBUG:ouimeaux.discovery:Received a response from 192.168.0.10:1900
DEBUG:ouimeaux.discovery:Received a response from 192.168.0.1:1901
DEBUG:ouimeaux.discovery:Received a response from 192.168.0.10:47131
DEBUG:ouimeaux.discovery:Broadcasting M-SEARCH to 239.255.255.250:1900
DEBUG:ouimeaux.discovery:Received a response from 192.168.0.10:1900
DEBUG:ouimeaux.discovery:Received a response from 192.168.0.1:1901
DEBUG:ouimeaux.discovery:Received a response from 192.168.0.10:56836
.1 is the router and .10 is the rpi. I've read (similar) issue 25 but I only have one router (which was the cause).
What am I doing wrong?

**Comment by iancmcc** [comment]
It looks like your router isn't routing UDP traffic. Make sure UPnP is enabled, or that the firewall is disabled. Or punch a hole for udp/1900.

**Comment by nfgb** [comment]
Hi,
It shouldn't be the problem since I frequently use minidlna and other upnp servers/clients.
In this case these wouldn't work either right?

**Comment by iancmcc** [comment]
Yeah, that's right. Hmm. I honestly don't know why you wouldn't get any responses except from the router and the RPi. Is anything else listening on that port on the pi? Either 54321 or 1900? Sometimes Spotify gets in the way on desktops, perhaps there's something else running.

**Comment by nfgb** [comment]
I don't use Spotify and I've tried with a different linux machine. I believe there were fixes to ouimeaux since my last attempt (6 months ago). May I'll try again later at home.
At the time i thought it would have be something to do with the firmware version of the wemo. Once again I've made some upgrades to the firmware since last attempt.
