### ISSUE TITLE
WeMo LED Light / WeMo Link

### ISSUE THREAD

**Issue by fritz-fritz** [iancmcc/ouimeaux#51]
Unfortunately it seems these (and other new wemo devices) are not yet supported.

It would be great to have ouimeaux be able to interact with the new WeMo LED Lights by using the Link much as I assume the wemo app communicates to them.

**Comment by ghctim** [comment]
Any closer to making this work?

**Comment by fritz-fritz** [comment]
Yes. I am close. Hopefully will submit a pull request soon.

**Comment by fritz-fritz** [comment]
@iancmcc , @ghctim , @mrose17 ,

Thanks to the documentation of @jescarri and @hardillb , I have gotten basic support implemented on [my fork](https://github.com/fritz-fritz/ouimeaux)... Next I need to work on adding support for the web server, testing, and docs before submitting a pull request. Feel free to check it out and make suggestions etc... I'm sure there is a better way this could have been done but I'm just happy I finally have Python API and CLI support!

**Comment by afm497** [comment]
@fritz-fritz 

The fork you mentioned above should be able to control the wemo bridge with led bulbs on it? I think that's what you are saying you are working on, but wanting to confirm. I've played around a bit with your fork and can't seem to get my wemo bulb bridge detected. Any pointers you might have for me looking to play around with controlling these led bulbs?

**Comment by fritz-fritz** [comment]
@afm497

Yes my fork should currently work for controlling Wemo LED bulbs through the bridge. At least for command line and Python usage. The REST API and web app are not yet supported.

I have yet to add documentation and other features. I have not tested or planned for bulbs that are grouped so that may be part of the problem you are having? Also try clearing your cache and then scanning again to see if it picks them up. Good luck!

**Comment by afm497** [comment]
@fritz-fritz 

works perfect. thanks very much for that, very useful. If it's of interest, the bridge/bulbs combo that I have locally had differrent light attributes that what was defined in ouimeaux.device.bridge
Spefically, there was no information in my setup for "manufacturer', 'model', and 'certified'

**Comment by fritz-fritz** [comment]
Support added with #75

**Comment by iancmcc** [comment]
This is in release 0.7.9 pretty much as-is. Thanks for all your work. Plan is to add server support and device events similar to switches in 0.8.

**Comment by hardillb** [comment]
I've been adding some Osram lightify bulbs to my Wemo Link. They work well but the WeMo Android app doesn't support Colours or Colour Temperature changes (despite showing it in the screen shots). I've been poking round to find the capabilities used to set these values and I've found that you can get the WeMo link to give you a list of all the ones it knows about and a description of the fields.

I've dumped the list here: https://gist.github.com/hardillb/ec88e86597d65584b1ba

Hope that helps you guys, My Node.js module is coming along nicely and I should have a nice Node-RED module based on it as well.

**Comment by fritz-fritz** [comment]
@hardillb Thanks so much for all the work you do! I definitely was using your previous gists as a starting point. Currently I'm working on adding Link/LED support to homebridge. If I had color bulbs I would definitely take a look. I'm sure it will be helpful to others!
