### ISSUE TITLE
Wemo Switches change their own port numbers

### ISSUE THREAD

**Issue by draythomp** [iancmcc/ouimeaux#55]
Many of the problems with the Wemo switches over a period of time are caused by the switches themselves changing the port number they respond to.  Roughly every three days their wall switches change the port number so http://192.168.0.15:49153 becomes http://192.168.0.15:49154.  The subscription is gone and the switch seems to disappear off the network because it's IP port has changed.

I documented how I found this and what I did about it in my code on my blog at http://www.desert-home.com/2014/11/wemo-light-switches-and-intermittent.html, but my solution may not be directly applicable to this code.

**Comment by balloob** [comment]
This explains so much, thank you sir!

The best way to approach this is that when we get a connection refused error, we search the network again with SSDP, but this time use the device specific udn `switch._config.get_UDN()` (example value: `uuid:Insight-1_0-221346K1200409`). Once we found the new location, we update the object to point at the new host/port and all should be well..

**Comment by mrose17** [comment]
+1

**Comment by balloob** [comment]
I just pushed a fix for this to [pywemo](https://github.com/balloob/pywemo) (a stripped down version of ouimeaux). Since the code base for devices is equal, it should be easy to be ported to ouimeaux. The only difference is the discovery code. [You can find the commit here.](https://github.com/balloob/pywemo/commit/93fb98f1191266441dc0832f1b3f6fe2950399fe)

This is the output now on PyWemo, I unplugged the switch before the call to `switch.toggle()` and plugged it back in after the error message showed up.
```
>>> switch.toggle()
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.10
ERROR:pywemo.ouimeaux_device.api.service:Error communicating with Christmas Tree.
INFO:pywemo.ouimeaux_device:Trying to reconnect with Christmas Tree
INFO:pywemo.ouimeaux_device:Not found in try 0. Trying again in 0 seconds
INFO:pywemo.ouimeaux_device:Not found in try 1. Trying again in 5 seconds
INFO:pywemo.ouimeaux_device:Not found in try 2. Trying again in 10 seconds
INFO:pywemo.ouimeaux_device:Not found in try 3. Trying again in 15 seconds
INFO:pywemo.ouimeaux_device:Not found in try 4. Trying again in 20 seconds
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.10
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.10
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.10
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.10
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.10
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.10
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.10
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.10
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.10
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.10
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.10
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.10
INFO:pywemo.ouimeaux_device:Found it again, updating local values
```

**Comment by jaywiseman1971** [comment]
I have put a bounty up on the OpenHAB WeMo binding changing ports also; any takers?

https://www.bountysource.com/issues/73078259-wemo-devices-changing-ports

Best, Jay
