### ISSUE TITLE
wemo insight status

### ISSUE THREAD

**Issue by axelderhund** [iancmcc/ouimeaux#57]
Hello,
I'm a complete noob when it comes to python, however i'm good with bash scripting. I like the implimentation of cli.py, however it doesnt have a method to check the status of an Insight switch's metrics. I see there is API documentation for the insight, however I dont know how to call this within cli.py. It'd really be great if I could run the following command 'wemo insight tv status', or 'wemo switch tv insight' and have the Insight's metrics printed to the screen. Does anyone have an example to bring this into the program?

Also, when running wemo from a raspberry pi, it takes about 5 seconds for it to execute a toggle command. Is there any way to cut this time down by specifying the IP address of the wemo, so it can skip the discovery phase of the program? Is there any way to cut this time down?

Thanks!

**Comment by iancmcc** [comment]
See #41 for a possible integration. I'll go through it this week for 0.7.4.
