### ISSUE TITLE
[Errno 98] - Address already in use: ('', 8989)

### ISSUE THREAD

**Issue by RobSmith2** [iancmcc/ouimeaux#63]
Hi, 

I've got some code similar to whats in the watch.py example as a function which I'll call as a thread. 

t1 = threading.Thread(target=FUNCTIONREFERENCEHERE, args=(target,))
t1.start()

The thread will be controlled by loop querying a getter/setter value. I've found I can start and stop the thread easily and the switch functionality stops and starts correctly. However I've found that until the whole program which spawned the thread ends the tcp connection is still open on port 8989. Ideally I want to have several modules, all with unique functionality and be able to call them in threads (so my main programme with continue) sequentially. I never want to call them simultaneously (as they work on there same switch). I've tried adding a;

os.system("kill -9 $(lsof -i:8989 -t)")

to the code within the function which creates and monitors the env variable but upon execution it kills the whole programme (the main.py) not just the spawned thread. I think what I'm looking for is something along the lines of a env.free()/env.stop() however all I can find in the code base is;

class StopBroadcasting(Exception):
    pass

If i'm doing something wrong or i've missed something it'd be great to have some input, thanks!

**Comment by balloob** [comment]
The problem is probably related to sockets not being initialized by being allowed to be reused. See the bottom of [this page](https://docs.python.org/2/library/socket.html) how to prevent it.

**Comment by RobSmith2** [comment]
Thanks for the reply; 

I've checked out the link and compared it with what I can see and the state is staying in Listen, not in stay-alive. 

I suspect what is happening is the port is being bound to the main.py process which kicks off the thread, then it isn't released until the main.py ends. I guess my options are to change it from a thread to a subprocess which can inherit the port but and then be safely killed without killing the main.py (but i'd have to change my getter setter) or to wait for a proper method to be implemented to safely unallocated the port and stop listening. Thanks for the input though!
