### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by bobbylox** [iancmcc/ouimeaux#72]
using either easy_install or setup.py install fails on Mac OSX, showing the following error:

`configure: error: in`/private/tmp/easy_install-0vqa0V/gevent-1.0.1/build/temp.macosx-10.6-intel-2.7/libev':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
unable to execute gcc-4.2: No such file or directory
error: Setup script exited with error: command 'gcc-4.2' failed with exit status 1
`

**Comment by ahmadtawakol** [comment]
You need to have gcc installed.

You can install gcc by installing Command Line Tools for Xcode from [Apple's developer page here](https://developer.apple.com/downloads/index.action) (you need a free account first, but you probably already have one if you have an iCloud account.) 

After installing it, just try installing ouimeaux again and it should work.

You can check if you have gcc installed by running the following command: 
```
$ gcc -v
````

If gcc is installed, you should get something similar to the following:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```

If you don't have gcc installed, you'll just get
```
-bash: gcc: command not found
```
