### ISSUE TITLE
ouimeaux 0.7.3 always crashes 

### ISSUE THREAD

**Issue by twodice** [iancmcc/ouimeaux#73]
On a 5K iMac with 10.10.2, via the command line:

```
$ wemo list
python(5890,0x7fff77f02300) malloc: *** mach_vm_map(size=18446744073599025152) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
```

or via the api:

```
In [1]: from ouimeaux.environment import Environment

In [2]: env = Environment()

In [3]: env.start()
python(5879,0x7fff77f02300) malloc: *** mach_vm_map(size=18446744073599025152) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
```

**Comment by fritz-fritz** [comment]
This is a memory allocation error.

While I don't know enough about them to help you resolve the issue, I would suggest you ensure that your python environment is installed properly and up to date. Apple ships a custom version of python so who knows that may be the problem... It is generally recommending to install from the [Official Python Source](https://www.python.org/downloads/).
