### ISSUE TITLE
Error with Bridge

### ISSUE THREAD

**Issue by ahmadtawakol** [iancmcc/ouimeaux#77]
When I run `wemo list` or `wemo status`, I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pysignals/dispatcher.py", line 197, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/alfrd/ouimeaux-master/ouimeaux/environment.py", line 146, in _found_device
    log.info("Found device %r at %s" % (device, address))
  File "/home/alfrd/ouimeaux-master/ouimeaux/device/bridge.py", line 14, in __repr__
    self.bridge_get_lights()
  File "/home/alfrd/ouimeaux-master/ouimeaux/device/bridge.py", line 21, in bridge_get_lights
    endDevices = self.bridge.GetEndDevices(DevUDN=UDN,ReqListType='PAIRED_LIST').get('DeviceLists')
  File "/home/alfrd/ouimeaux-master/ouimeaux/device/api/service.py", line 50, in __call__
    response = requests_post(self.controlURL, body.strip(), headers=self.headers)
  File "/home/alfrd/ouimeaux-master/ouimeaux/utils.py", line 80, in inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='192.168.1.184', port=49154): Read timed out. (read timeout=1)
<Greenlet at 0x1d9c030: <bound method Signal.send of <pysignals.dispatcher.Signal object at 0x1b98ff0>>(<ouimeaux.discovery.UPnP object at 0x1d6ac90>, headers={'opt': '"http://schemas.upnp.org/upnp/1/0/"; ns=0, address=('192.168.1.184', 3920))> failed with ReadTimeout
```

**Comment by ahmadtawakol** [comment]
Commenting out line number `75` in `utils.py` (`kwargs['timeout'] = 1`) fixes the problem

**Comment by fritz-fritz** [comment]
Interesting.

FYI I found when there was an existing cache from a previous version of ouimeaux it was beneficial to clear the cache the first time before running either ```wemo list``` or ```wemo status```

**Comment by ahmadtawakol** [comment]
@fritz-fritz I tried that as well, I also tried running the same commands with `--no-cache` and it still gave the same error. I have the timeout now set to 30 and it seems to be working, I don't really know what that means or how it might affect the rest of the code though.

**Comment by fritz-fritz** [comment]
I have now confirmed this issue. I slowly tested and incremented up from the initial 1 to 3 seconds and finally to 5 seconds. I believe 5 seconds should be high enough from my testing. Perhaps you could test it at five and see if you can reproduce the issue for me. If it is fixed at five I will submit a pull request to fix this.

I believe the issue stems on waiting for the bridge device to in turn talk to the bulbs on the other protocol (Zigbee?) It may need to be higher than five in environments with larger distances between the bulbs and bridge though unfortunately I cannot test this in my apartment.

**Comment by ahmadtawakol** [comment]
@fritz-fritz Sorry for taking so long.

So, funny thing...1 second now works for me.
I have no idea what happened. But I'm going to keep it at 5 for now.

**Comment by fritz-fritz** [comment]
@ahmadtawakol No worries, There may be a more elegant way to trap the error for if and when it does arise but I think setting the timeout to 5 seems like a reasonable precaution in the meantime.

This change may get included with the pull request #81 I just submitted to address the bug from the new firmware.

**Comment by fritz-fritz** [comment]
Hmm... I seem to have the issue again. It seems to me that it is a caching issue as when this error occurs it is repeatable but running ```wemo --no-cache list``` has no issue. I will have to investigate further.

**Comment by fritz-fritz** [comment]
Maybe related to #55

**Comment by ahmadtawakol** [comment]
I *always* use `--no-cache`. The cache doesn't work very well and it's very buggy, and I think ian said he wanted to remove it at all.

Also, from my testing, it seems as though `--no-cache` still uses the cache file, it just doesn't update it. So if you run a `wemo` command without `--no-cache` and then run it again with it, it will still use the cache that is already saved, so you need to delete the cache file under `~/.wemo` and run `wemo clear` just in case

**Comment by fritz-fritz** [comment]
No I don't think I agree with you there. Without the ```--no-cache``` I currently cannot execute a ```wemo list``` or ```wemo status```. You may be right that it is using the known IPs for discovery but it certainly is not using the ports or else it would continue to fail. Perhaps this would function better if the default caching behavior was simply to store the known IPs for rediscovery of the current port. I would think the ```--no-cache``` flag should indicate complete new discovery of wemo devices and not store them.

Regardless, to fix this issue it sounds like i need to trap the error and make it rediscover the port.
