### ISSUE TITLE
Firmware update causes ouimeaux to throw an attribute error

### ISSUE THREAD

**Issue by SethHaines** [iancmcc/ouimeaux#78]
Just upgraded to wemo firmware: 
WeMo_WW_2.00.8326.PVT-OWRT-SNS on all the switches from WeMo_US_2.00.7166.PVT. 

Ouimeaux server upon start-up now shows: 
```
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.6/site-packages/pysignals/dispatcher.py", line 197, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/lib/python2.6/site-packages/ouimeaux/environment.py", line 137, in _found_device
    device = klass(headers['location'])
  File "/usr/lib/python2.6/site-packages/ouimeaux/device/__init__.py", line 28, in __init__
    service = Service(svc, base_url)
  File "/usr/lib/python2.6/site-packages/ouimeaux/device/api/service.py", line 72, in __init__
    for action in self._svc_config.get_action():
AttributeError: 'NoneType' object has no attribute 'get_action'
<Greenlet at 0x1aeeeb0: <bound method Signal.send of <pysignals.dispatcher.Signal object at 0x16fac10>>(<ouimeaux.discovery.UPnP object at 0x1b68f90>, headers={'opt': '"http://schemas.upnp.org/upnp/1/0/"; ns=0, address=('192.168.1.5', 3083))> failed with AttributeError
```
Using version: ouimeaux (0.7.3) installed by pip.

Firmware update changed the attribute response?

**Comment by fritz-fritz** [comment]
FYI: I am not running that firmware on any of my switches and I do not see an option to upgrade. My switches are all still on WeMo_US_2.00.7166.PVT.

This shouldn't be too hard to fix if wemo continues to roll out the firmware ( so i can update a switch and test ). Though its possible they pulled it. I'll continue to keep a look out.

**Comment by SethHaines** [comment]
Hi Fritz, 

Thank you for the reply.  Agreed, 7166 works perfectly.  Luckily I still have some switches that weren't updated, so I'm able to see some of my house. :) 

Happy to assist in the troubleshooting if you'll let me. I can dump details of command responses if you want to shoot over what info you're looking for.  If there's a way to manually export firmware from the wemo devices, I can post that up as well. 

Respectfully, 

Seth

**Comment by asubd** [comment]
I am also running into this exact same error after updating the firmware on the plug, but both of my  switches are ok even after the firmware update.
FW versions :Plug - 2.00.8326.PVT-OWRT-SNS

**Comment by asubd** [comment]
continuing the previous message - 
FW version : Switch - 2.00.8137.PVT-OWRT-LS

Happy to help in troubleshooting.

Thanks

AS

**Comment by fritz-fritz** [comment]
Finally was prompted to upgrade firmware. Found an upgrade for both my switches and my Link (bridge). Release notes for switch FW mention "architectural change for future scalability". I am upgrading two of my switches now to test further.

I will update with my findings and will send a pull request if I have a fix.

**Comment by asubd** [comment]
Yep that works, no side effects noticed yet. Thanks for the quick workaround.

**Comment by fritz-fritz** [comment]
Glad to hear it's working for you too!

Maybe @iancmcc could weigh in on if this is an appropriate fix?

**Comment by iancmcc** [comment]
I will certainly check when I get a chance.

**Comment by SethHaines** [comment]
Thank you Fritz!  Patch works great!

**Comment by iancmcc** [comment]
No problems that I see! Thanks!

**Comment by oulmot** [comment]
thanks @fritz-fritz

**Comment by oulmot** [comment]
0.7.9 updated with fritz-fritz's fix.

sudo pip uninstall ouimeaux
sudo pip install ouimeaux
