### ISSUE TITLE
Inconsistent Light State

### ISSUE THREAD

**Issue by fritz-fritz** [iancmcc/ouimeaux#79]
I'm submitting this issue as partly a reminder to myself to fix this and partly as a request for others to review my code (I wrote the bridge support which enables the LED Lights).

Specifically I can reproduce this when feeding wemo this:
```wemo light <lightname> off 255```
The bulbs do not like to receive a dim setting when being asked to turn off as this would break the slow dim effect built into the bulb.
This produces a status like this:
```Light: <lampname> 	{'dim': '255', 'state': '255'}```
I believe this is what is being returned from the bulb and not an issue with my code (unsure). Obviously this could cause problems and so we need to ensure that these issues are addressed:

1. Ensure only good data is fed to the bulbs
2. Ensure rate of data sent to bulbs is controlled (have caused bulbs to act funny by sending too many requests quickly)
3. Error check response from bulbs

FYI: (To quickly switch off a light without the dim effect you can tell the bulb ```wemo light <lightname> on 0``` meaning to turn on and set dim to zero)

**Comment by jluke1** [comment]
I get the same status just using the off command.

melba:~ jluke$ /usr/local/bin/wemo light Light1 status
{'dim': '255', 'state': '1'}
melba:~ jluke$ wemo light 'Light1' off
melba:~ jluke$ /usr/local/bin/wemo light Light1 status
{'dim': '255', 'state': '255'}
This also has the side effect of greying out the app button
with the "Not Detected" message. See attached screen shots.

Macbook Pro
Mac OS 10.10.3
iOS 8.3

![img_0071](https://cloud.githubusercontent.com/assets/11991080/7206016/dd7c1b76-e570-11e4-86ae-ad59a734b2e2.jpg)

![img_0069](https://cloud.githubusercontent.com/assets/11991080/7206079/50662d7a-e571-11e4-99d6-0074378d3a85.jpg)
![img_0070](https://cloud.githubusercontent.com/assets/11991080/7206080/52320688-e571-11e4-8f9b-d06986ba10fd.jpg)

Thanks for your work with ouimeaux, much appreciated.
John Luke

**Comment by fritz-fritz** [comment]
Closing due to #123 (without testing)
