### ISSUE TITLE
ouimeaux from amazon cloud

### ISSUE THREAD

**Issue by agt24** [iancmcc/ouimeaux#86]
I've had limited success controlling my WeMo Maker using IFTTT. The time resolution is just too course.

I was hoping to try to control it using ouimeaux running on an amazon cloud instance along with some clever port forwarding. But based on the comments in issue #80, it doesn't sound like this is possible. Is that accurate?

**Comment by iancmcc** [comment]
It would be possible, if you could specify static IPs for your wemo devices. I'm guessing multicast isn't going to fly in a VPC. 




It would not be a crazy feature addition. The cache already does it, just awkwardly and buggily. The hook is there, though.

**Comment by agt24** [comment]
Ah, good. I actually have a budget for this project so if anyone is interested in working on this feature please send me a message.

**Comment by iancmcc** [comment]
I'll happily add the feature. It's been needed for a log time but I haven't had the time.

**Comment by agt24** [comment]
Thanks! Let me know if I can help at all. I can give you access to my cloud instance if you want.

**Comment by psolanke** [comment]
Is the bounty for this issue still on offer?
