### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by eprompc** [iancmcc/ouimeaux#90]
There is a new update. Can we update without fear??? Any issue report?

**Comment by 2oh1** [comment]
This may sound like a silly question, but...  how do I update?  Do I install it over itself, or is there another way?  I've searched the docs but can't find info on how to update to a new version.

**Comment by iancmcc** [comment]
Same as any Python package. pip install --upgrade ouimeaux.

**Comment by rgardner** [comment]
I think @eprompc means that there is a firmware update available for the wemo devices. My phone is giving me the option to update. I haven't updated and don't plan to; I haven't found any docs on downgrading from a bad wemo update that breaks this library.
